/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/rulesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rulesets */
        get: operations["rulesets_api_v1_rulesets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scans */
        get: operations["list_scans_api_v1_scans_get"];
        put?: never;
        /** Submit Scan */
        post: operations["submit_scan_api_v1_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_api_v1_scans__identity__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{identity}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Changes */
        get: operations["changes_api_v1_scans__identity__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{identity}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_api_v1_scans__identity__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{identity}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results Page */
        get: operations["results_page_api_v1_scans__identity__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{identity}/results/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result Detail */
        get: operations["result_detail_api_v1_scans__identity__results__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{identity}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_v1_scans__identity__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{identity}/reviews/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Review */
        put: operations["put_review_api_v1_scans__identity__reviews__instrument_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{identity}/series/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series */
        get: operations["series_api_v1_scans__identity__series__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sessions Current
         * @description Latest completed market session; read-only scheduling input.
         */
        get: operations["sessions_current_api_v1_sessions_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_api_v1_watchlists_get"];
        put?: never;
        /** Create Watchlist */
        post: operations["create_watchlist_api_v1_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{identity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_api_v1_watchlists__identity__get"];
        put?: never;
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_api_v1_watchlists__identity__delete"];
        options?: never;
        head?: never;
        /** Patch Watchlist */
        patch: operations["patch_watchlist_api_v1_watchlists__identity__patch"];
        trace?: never;
    };
    "/api/v1/watchlists/{identity}/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Symbols */
        put: operations["put_symbols_api_v1_watchlists__identity__symbols_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Change */
        Change: {
            /** Codes */
            codes: ("NEW_CANDIDATE" | "DROPPED_CANDIDATE" | "STAGE_CHANGED" | "SCORE_CHANGED" | "WINDOW_CHANGED" | "UNIVERSE_CHANGED" | "COMPARISON_UNAVAILABLE" | "DATA_REVISION_DIFF" | "NO_BASELINE")[];
            current?: components["schemas"]["SymbolAnalysis"] | null;
            /** Instrument Id */
            instrument_id?: string | null;
            previous?: components["schemas"]["SymbolAnalysis"] | null;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Symbol */
            symbol?: string | null;
        };
        /** Comparison */
        Comparison: {
            /**
             * Binding
             * @default recorded
             * @enum {string}
             */
            binding: "recorded" | "legacy_unavailable" | "replay_unavailable";
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["Change"][];
            /**
             * Current Session
             * Format: date
             */
            current_session: string;
            /** Previous Run Id */
            previous_run_id?: string | null;
            /**
             * Previous Session
             * Format: date
             */
            previous_session: string;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /**
             * Semantic Version
             * @default 1
             * @constant
             */
            semantic_version: 1;
        };
        /** CountsOut */
        CountsOut: {
            /** Candidate */
            candidate: number;
            /** Data Error */
            data_error: number;
            /** Evaluated */
            evaluated: number;
            /** Excluded */
            excluded: number;
            /** Requested */
            requested: number;
        };
        /** CreateScan */
        CreateScan: {
            /** As Of Session */
            as_of_session?: string | null;
            /** @default auto */
            data_mode: components["schemas"]["DataMode"];
            /**
             * Ruleset Id
             * @default breakout-v1
             * @constant
             */
            ruleset_id: "breakout-v1";
            /**
             * Watchlist Id
             * Format: uuid
             */
            watchlist_id: string;
        };
        /** CreateWatchlist */
        CreateWatchlist: {
            /** Name */
            name: string;
            /** Symbols */
            symbols: string[];
        };
        /**
         * DataMode
         * @enum {string}
         */
        DataMode: "auto" | "cache_only" | "force";
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Details */
            details?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Message */
            message: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "WORKER_INTERRUPTED" | "NO_DATA" | "STALE_DATA" | "MISSING_REQUIRED_SESSION" | "INVALID_CLOSE" | "CONFLICTING_DUPLICATE" | "INSUFFICIENT_HISTORY" | "UNSUPPORTED_INSTRUMENT" | "SUSPICIOUS_FLAT_SERIES" | "ADJUSTMENT_REVIEW_REQUIRED" | "INVALID_AS_OF_SESSION" | "SESSION_NOT_COMPLETE" | "WATCHLIST_VERSION_CONFLICT" | "WATCHLIST_IN_USE" | "SCAN_NOT_READY" | "SCAN_FAILED" | "EXECUTION_INCOMPATIBLE" | "IDEMPOTENCY_CONFLICT" | "REVIEW_REVISION_CONFLICT" | "QUEUE_LIMIT_REACHED" | "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "PAYLOAD_TOO_LARGE" | "INTERNAL_ERROR" | "REPORT_ERROR";
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** InstrumentOut */
        InstrumentOut: {
            /** Currency */
            currency: string;
            /** Display Symbol */
            display_symbol: string;
            /** Exchange */
            exchange: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Type */
            instrument_type: string;
        };
        JsonValue: unknown;
        /** PatchWatchlist */
        PatchWatchlist: {
            /** Expected Revision */
            expected_revision: number;
            /** Name */
            name: string;
        };
        /** ProgressOut */
        ProgressOut: {
            /**
             * Phase
             * @enum {string}
             */
            phase: "market_data" | "analysis" | "publication";
            /** Processed Symbols */
            processed_symbols: number;
            /** Total Symbols */
            total_symbols: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PutReview */
        PutReview: {
            /** Expected Revision */
            expected_revision?: number | null;
            /**
             * Label
             * @enum {string}
             */
            label: "worth_reviewing" | "borderline" | "not_useful";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Reason */
        Reason: {
            /** Code */
            code: string;
            /**
             * Parameters
             * @default {}
             */
            parameters: {
                [key: string]: number | string;
            };
        };
        /** ReplaceSymbols */
        ReplaceSymbols: {
            /** Expected Revision */
            expected_revision: number;
            /** Symbols */
            symbols: string[];
        };
        /**
         * ResultOut
         * @description Full per-symbol detail; never included in polling/status payloads.
         */
        ResultOut: {
            /** Alternative Windows */
            alternative_windows: components["schemas"]["WindowAnalysis"][];
            analysis: components["schemas"]["SymbolAnalysis"];
            /**
             * Category
             * @enum {string}
             */
            category: "evaluated" | "excluded" | "data_error";
            instrument: components["schemas"]["InstrumentOut"];
            /** Rank */
            rank: number | null;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /** Warnings */
            warnings: string[];
        };
        /** ResultsPage */
        ResultsPage: {
            /** Items */
            items: components["schemas"]["ResultOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ReviewsPage */
        ReviewsPage: {
            /** Items */
            items: components["schemas"]["SavedReviewOut"][];
        };
        /** RulesetOut */
        RulesetOut: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Minimum History */
            minimum_history: number;
            /** Version */
            version: string;
            /** Windows */
            windows: number[];
        };
        /** SavedReviewOut */
        SavedReviewOut: {
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Label */
            label: string;
            /** Note */
            note: string;
            /** Revision */
            revision: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScanAccepted */
        ScanAccepted: {
            /**
             * As Of Session
             * Format: date
             */
            as_of_session: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            links: components["schemas"]["ScanLinks"];
            /** Ruleset Version */
            ruleset_version: string;
            /**
             * State
             * @default QUEUED
             * @constant
             */
            state: "QUEUED";
            /** Watchlist Revision */
            watchlist_revision: number;
        };
        /** ScanContext */
        ScanContext: {
            /**
             * As Of Session
             * Format: date
             */
            as_of_session: string;
            /** Engine Version */
            engine_version: string;
            /**
             * Reference Session
             * Format: date
             */
            reference_session: string;
        };
        /** ScanLinks */
        ScanLinks: {
            /** Changes */
            changes: string;
            /** Export */
            export: string;
            /** Results */
            results: string;
            /** Self */
            self: string;
            /** Watchlist */
            watchlist: string;
        };
        /**
         * ScanStatusOut
         * @description Light polling document: identity, state, sessions, progress, coverage, links.
         */
        ScanStatusOut: {
            /**
             * As Of Session
             * Format: date
             */
            as_of_session: string;
            counts?: components["schemas"]["CountsOut"] | null;
            /** Data Mode */
            data_mode: string;
            /** Engine Version */
            engine_version: string;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            links: components["schemas"]["ScanLinks"];
            progress?: components["schemas"]["ProgressOut"] | null;
            /**
             * Reference Session
             * Format: date
             */
            reference_session: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Ruleset Id */
            ruleset_id: string;
            /** Ruleset Version */
            ruleset_version: string;
            /** Source Run Id */
            source_run_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** State */
            state: string;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /**
             * Watchlist Id
             * Format: uuid
             */
            watchlist_id: string;
            /** Watchlist Revision */
            watchlist_revision: number;
        };
        /** ScansPage */
        ScansPage: {
            /** Items */
            items: components["schemas"]["ScanStatusOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** SeriesOut */
        SeriesOut: {
            /**
             * As Of Session
             * Format: date
             */
            as_of_session: string;
            /** Close Resistance */
            close_resistance?: number | null;
            /** Closes */
            closes: number[];
            /** Displayed Sessions */
            displayed_sessions: number;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Price Basis */
            price_basis: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sessions */
            sessions: string[];
            /** Sma */
            sma: {
                [key: string]: (number | null)[];
            };
            /** Symbol */
            symbol: string;
            /** Window End */
            window_end?: string | null;
            /** Window Start */
            window_start?: string | null;
        };
        /**
         * SessionOut
         * @description Latest completed market session new scans would use.
         */
        SessionOut: {
            /**
             * As Of Session
             * Format: date
             */
            as_of_session: string;
            /**
             * Reference Session
             * Format: date
             */
            reference_session: string;
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "FORMING" | "NEAR_CLOSE_RESISTANCE" | "CLOSE_BREAK_ABOVE" | "EXTENDED";
        /** SymbolAnalysis */
        SymbolAnalysis: {
            /**
             * Alternative Windows
             * @default []
             */
            alternative_windows: components["schemas"]["WindowAnalysis"][];
            /** Config Hash */
            config_hash: string;
            context: components["schemas"]["ScanContext"];
            /**
             * Evaluation Status
             * @enum {string}
             */
            evaluation_status: "EVALUATED" | "DATA_UNAVAILABLE";
            /**
             * Features
             * @default {}
             */
            features: {
                [key: string]: number | null;
            };
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Is Candidate
             * @default false
             */
            is_candidate: boolean;
            /**
             * Liquidity
             * @default NOT_EVALUATED
             * @constant
             */
            liquidity: "NOT_EVALUATED";
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["Reason"][];
            /** Score */
            score?: number | null;
            selected_window?: components["schemas"]["WindowAnalysis"] | null;
            stage?: components["schemas"]["Stage"] | null;
        };
        /** WatchlistLinks */
        WatchlistLinks: {
            /** Self */
            self: string;
            /** Symbols */
            symbols: string;
        };
        /** WatchlistOut */
        WatchlistOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            links: components["schemas"]["WatchlistLinks"];
            /** Name */
            name: string;
            /** Revision */
            revision: number;
            /** Symbols */
            symbols: string[];
        };
        /** WindowAnalysis */
        WindowAnalysis: {
            /** Available */
            available: boolean;
            /**
             * Eligible
             * @default false
             */
            eligible: boolean;
            /**
             * Features
             * @default {}
             */
            features: {
                [key: string]: number | null;
            };
            /**
             * Is Close Break
             * @default false
             */
            is_close_break: boolean;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["Reason"][];
            /** Score */
            score?: number | null;
            /**
             * Score Breakdown
             * @default {}
             */
            score_breakdown: {
                [key: string]: number;
            };
            stage?: components["schemas"]["Stage"] | null;
            /** Window Sessions */
            window_sessions: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rulesets_api_v1_rulesets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesetOut"][];
                };
            };
        };
    };
    list_scans_api_v1_scans_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScansPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    submit_scan_api_v1_scans_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScan"];
            };
        };
        responses: {
            /** @description Idempotency-key replay: current status of the original scan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStatusOut"];
                };
            };
            /** @description Scan accepted for asynchronous execution */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_scan_api_v1_scans__identity__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    changes_api_v1_scans__identity__changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted comparison against the bound baseline run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    export_csv_api_v1_scans__identity__export_get: {
        parameters: {
            query?: {
                format?: "csv";
                all_results?: boolean;
            };
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV report download */
            200: {
                headers: {
                    /** @description Attachment filename for the scan report */
                    "Content-Disposition"?: string;
                    "X-Result-Count"?: number;
                    "X-Scan-State"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    results_page_api_v1_scans__identity__results_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                stage?: string | null;
                candidate?: boolean | null;
            };
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    result_detail_api_v1_scans__identity__results__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_reviews_api_v1_scans__identity__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    put_review_api_v1_scans__identity__reviews__instrument_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    series_api_v1_scans__identity__series__instrument_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                identity: string;
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    sessions_current_api_v1_sessions_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    list_watchlists_api_v1_watchlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"][];
                };
            };
        };
    };
    create_watchlist_api_v1_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWatchlist"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_watchlist_api_v1_watchlists__identity__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_watchlist_api_v1_watchlists__identity__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    patch_watchlist_api_v1_watchlists__identity__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchWatchlist"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    put_symbols_api_v1_watchlists__identity__symbols_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identity: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceSymbols"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
